### ISSUE TITLE
bot not starting

### ISSUE THREAD

**Issue by f7b** [CodingGarden/twitch-team-shoutout-bot#3]
Hi, after installing nodejs and npm (sudo apt-get install nodejs npm) forwarded with "npm i"
I'm getting following:

$ npm start

> livecoder-shoutout-bot@1.0.0 start
> node src/index.js

file:///home/ubuntu/sobot/src/index.js:43
    const name = displayName ?? username;
                                                  ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/ubuntu/sobot
npm ERR! command failed
npm ERR! command sh -c node src/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-09-13T10_45_59_446Z-debug.log

/home/ubuntu/.npm/_logs/2021-09-13T10_45_59_446Z-debug.log:
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.21.0
3 timing config:load:defaults Completed in 10ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 11ms
5 timing config:load:builtin Completed in 12ms
6 timing config:load:cli Completed in 12ms
7 timing config:load:env Completed in 2ms
8 timing config:load:file:/home/ubuntu/sobot/.npmrc Completed in 1ms
9 timing config:load:project Completed in 4ms
10 timing config:load:file:/home/ubuntu/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 3ms
17 timing config:load:setEnvs Completed in 6ms
18 timing config:load Completed in 56ms
19 verbose npm-session 5e2b39ff18bde0a5
20 timing npm:load Completed in 112ms
21 timing command:run-script Completed in 602ms
22 timing command:start Completed in 617ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:314:20)
23 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24 verbose pkgid livecoder-shoutout-bot@1.0.0
25 verbose cwd /home/ubuntu/sobot
26 verbose Linux 5.11.0-1017-raspi
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v12.21.0
29 verbose npm  v7.5.2
30 error code 1
31 error path /home/ubuntu/sobot
32 error command failed
33 error command sh -c node src/index.js
34 verbose exit 1

**Comment by f7b** [comment]
Please disregard, issue solved with upgrading to npm v14.
