### ISSUE TITLE
Bot not starting after upgrading

### ISSUE THREAD

**Issue by f7b** [CodingGarden/twitch-team-shoutout-bot#8]
$ npm version
{
  'livecoder-shoutout-bot': '1.1.0',
  npm: '8.5.4',
  node: '14.17.6',
  v8: '8.4.371.23-node.76',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1l',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}

$ npm start &
[1] 3219
> livecoder-shoutout-bot@1.1.0 start
> node src/index.js

(node:3234) UnhandledPromiseRejectionWarning: Error: Request failed with status code 401
    at createError (/home/ubuntu/shoutout/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/shoutout/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/shoutout/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3234) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
[1]+  Done                    npm start

**Comment by f7b** [comment]
Does "Request failed with status code 401" point to invalid data in .env file ?

**Comment by f7b** [comment]
*facepalm*
